### PR TITLE
`/x/net/http` upgrade breaking change

### PR DESCRIPTION
**Pull request by gzuidhof**
I added a test case that breaks when you upgrade `golang.org/x/net`, which broke the [Hermes e-mail templating package](https://github.com/matcornic/hermes) downstream.

This requires a downstream update of `goquery`, and `/x/net/http`. I believe that /x/net/http was resolved, but Goquery hasn't upgraded yet https://github.com/PuerkitoBio/goquery/issues/391. After it has, the version here should be bumped too.

### CODE REVIEW

**Comment by bensie** [comment]
Seeing the same issue here, where conditional comments are broken:

Old output

```
<!--[if mso]>\n      <style type=\"text/css\">\n...
```

New (bad) output

```
<!--[if mso]&gt;\n      &lt;style type=&#34;text/css&#34;&gt;\n...
```

**Comment by vanng822** [comment]
Can anyone help me following those issues and upgrades? thanks

**Comment by bensie** [comment]
After additional digging, this issue is not resolved in x/net. I've added a note to https://github.com/golang/go/issues/46261 indicating where the bug was introduced.

**Comment by vanng822** [comment]
[dependabot](https://github.com/apps/dependabot) upgraded golang.org/x/net and it seems work fine?

**Comment by vanng822** [comment]
Look like it works fine so I will merge.

**Pull request merged**
